defaults: &defaults
  twitter_consumer_key: ""
  twitter_consumer_secret: ""
  twitter_access_token: ""
  twitter_access_token_secret: ""

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
