#!/bin/bash
export RAILS_ENV=test

run() {
  time bundle exec $*
}

echo "--- Starting continuous integration build"
./script/bundler

echo "--- Migrate the database from scratch"
run rake db:migrate:reset

echo "--- Running RSpec"
run rspec --color spec --format progress --format html --out rspec.html
rspec=$?

echo "--- Running Cucumber"
run cucumber features --profile ci --format html --out cucumber.html
cucumber=$?

if [[ $rspec -ne 0 || $cucumber -ne 0 ]]; then
  echo "--- Some tests have failed."
  exit 1
fi
